# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.4.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1047, 847)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.toolBox = QtWidgets.QToolBox(self.centralwidget)
        self.toolBox.setMinimumSize(QtCore.QSize(200, 0))
        self.toolBox.setMaximumSize(QtCore.QSize(200, 16777215))
        self.toolBox.setObjectName("toolBox")
        self.pageTree = QtWidgets.QWidget()
        self.pageTree.setGeometry(QtCore.QRect(0, 0, 200, 722))
        self.pageTree.setObjectName("pageTree")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.pageTree)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButtonCreateNew = QtWidgets.QPushButton(self.pageTree)
        self.pushButtonCreateNew.setObjectName("pushButtonCreateNew")
        self.gridLayout_2.addWidget(self.pushButtonCreateNew, 1, 0, 1, 1)
        self.pushButtonCopy = QtWidgets.QPushButton(self.pageTree)
        self.pushButtonCopy.setObjectName("pushButtonCopy")
        self.gridLayout_2.addWidget(self.pushButtonCopy, 2, 0, 1, 1)
        self.pushButtonChangeParent = QtWidgets.QPushButton(self.pageTree)
        self.pushButtonChangeParent.setObjectName("pushButtonChangeParent")
        self.gridLayout_2.addWidget(self.pushButtonChangeParent, 0, 0, 1, 1)
        self.pushButtonRemove = QtWidgets.QPushButton(self.pageTree)
        self.pushButtonRemove.setObjectName("pushButtonRemove")
        self.gridLayout_2.addWidget(self.pushButtonRemove, 4, 0, 1, 1)
        self.pushButtonDelete = QtWidgets.QPushButton(self.pageTree)
        self.pushButtonDelete.setObjectName("pushButtonDelete")
        self.gridLayout_2.addWidget(self.pushButtonDelete, 5, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 6, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.pageTree)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 3, 0, 1, 1)
        self.toolBox.addItem(self.pageTree, "")
        self.pageItem = QtWidgets.QWidget()
        self.pageItem.setGeometry(QtCore.QRect(0, 0, 96, 90))
        self.pageItem.setObjectName("pageItem")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.pageItem)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButtonStartTimer = QtWidgets.QPushButton(self.pageItem)
        self.pushButtonStartTimer.setObjectName("pushButtonStartTimer")
        self.gridLayout_3.addWidget(self.pushButtonStartTimer, 0, 0, 1, 1)
        self.pushButtonStopTimer = QtWidgets.QPushButton(self.pageItem)
        self.pushButtonStopTimer.setObjectName("pushButtonStopTimer")
        self.gridLayout_3.addWidget(self.pushButtonStopTimer, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 2, 0, 1, 1)
        self.toolBox.addItem(self.pageItem, "")
        self.horizontalLayout.addWidget(self.toolBox)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setRowCount(20)
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(True)
        self.horizontalLayout.addWidget(self.tableWidget)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setObjectName("tabWidget")
        self.horizontalLayout.addWidget(self.tabWidget)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1047, 29))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(-1)
        self.actionQuit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Tree Time"))
        self.pushButtonCreateNew.setText(_translate("MainWindow", "Create New Item"))
        self.pushButtonCopy.setText(_translate("MainWindow", "Copy to Child"))
        self.pushButtonChangeParent.setText(_translate("MainWindow", "Select New Parent"))
        self.pushButtonRemove.setText(_translate("MainWindow", "Remove Node"))
        self.pushButtonDelete.setText(_translate("MainWindow", "Delete Item"))
        self.pushButton.setText(_translate("MainWindow", "Copy to Sibling"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.pageTree), _translate("MainWindow", " Node Operations "))
        self.pushButtonStartTimer.setText(_translate("MainWindow", "Start Timer"))
        self.pushButtonStopTimer.setText(_translate("MainWindow", "Stop Timer"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.pageItem), _translate("MainWindow", " Field Operations "))
        self.tableWidget.setSortingEnabled(False)
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))

