# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[
        ('/usr/bin/acyclic', '.'),
        ('/usr/bin/bcomps', '.'),
        ('/usr/bin/ccomps', '.'),
        ('/usr/bin/cluster', '.'),
        ('/usr/bin/diffimg', '.'),
        ('/usr/bin/dijkstra', '.'),
        ('/usr/bin/dot_builtins', '.'),
        ('/usr/bin/dotty', '.'),
        ('/usr/bin/edgepaint', '.'),
        ('/usr/bin/gc', '.'),
        ('/usr/bin/gml2gv', '.'),
        ('/usr/bin/graphml2gv', '.'),
        ('/usr/bin/gv2gml', '.'),
        ('/usr/bin/gvcolor', '.'),
        ('/usr/bin/gvgen', '.'),
        ('/usr/bin/gvmap', '.'),
        ('/usr/bin/gvmap.sh', '.'),
        ('/usr/bin/gvpack', '.'),
        ('/usr/bin/gvpr', '.'),
        ('/usr/bin/gxl2gv', '.'),
        ('/usr/bin/lefty', '.'),
        ('/usr/bin/lneato', '.'),
        ('/usr/bin/mingle', '.'),
        ('/usr/bin/mm2gv', '.'),
        ('/usr/bin/nop', '.'),
        ('/usr/bin/prune', '.'),
        ('/usr/bin/sccmap', '.'),
        ('/usr/bin/tred', '.'),
        ('/usr/bin/unflatten', '.'),
        ('/usr/bin/vimdot', '.'),
        ('/usr/bin/circo', '.'),
        ('/usr/bin/dot', '.'),
        ('/usr/bin/dot2gxl', '.'),
        ('/usr/bin/fdp', '.'),
        ('/usr/bin/gv2gxl', '.'),
        ('/usr/bin/gxl2dot', '.'),
        ('/usr/bin/neato', '.'),
        ('/usr/bin/osage', '.'),
        ('/usr/bin/patchwork', '.'),
        ('/usr/bin/sfdp', '.'),
        ('/usr/bin/twopi', '.'),
        ('/usr/lib/x86_64-linux-gnu/graphviz', '.'),
        ('/usr/lib/x86_64-linux-gnu/libgvc.so.6.0.0', '.'),
        ('/usr/sbin/libgvc6-config-update', '.'),
        ('/usr/lib/x86_64-linux-gnu/libgvc.so.6', '.')
    ],
    datas=[('treetime/themes/', 'treetime/themes/'),
           ('/usr/lib/x86_64-linux-gnu/graphviz/config6a', 'config')],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='treetime',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
